version: "3.8"

services:
  trackmywealthserver:
    container_name: trackmywealth-server
    image: trackmywealth-server
    build:
      context: .
      target: development
    volumes:
      - .:/trackmywealth
    ports:
      - 4000:4000