version: "3.8"

services:
  trackmywealthdb:
    image: trackmywealth-database
    container_name: trackmywealth-database
    build:
      context: .
      target: db
    environment:
      - POSTGRES_USER=tmwapp
      - POSTGRES_PASSWORD=tmwv10
      - POSTGRES_DB=trackmywealth
    ports:
      - 5432:5432