version: "3.8"

services:
  trackmywealth:
    container_name: track-my-wealth-dev
    image: track-my-wealth-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/trackmywealth/src
    ports:
      - 3000:3000
