version: "3.8"

services:
  trackmywealthfrontend:
    container_name: track-my-wealth-frontend
    image: track-my-wealth-frontend
    build:
      context: .
      target: development
    volumes:
      - ./src:/trackmywealth/src
    ports:
      - 3000:3000
